/*
 * testpackage.gestiondinventaireyrm module that is visible to mvn package manager and build system
 * this file provide all requirements that depends on this project (UI , model , database)
 * generated by frontend developers 
 * @author aimeur abdelrahim , beliose ayoub
 * */
module testpackage.gestiondinventaireyrm {
	// external and internal librarys 
	requires javafx.controls;
	requires javafx.fxml;
	requires java.sql;

	requires org.controlsfx.controls;
	requires com.dlsc.formsfx;
	requires net.synedra.validatorfx;
	requires org.kordamp.ikonli.javafx;
	requires org.kordamp.bootstrapfx.core;

	// exports testpackage.model to javafx.fxml;
	// exports testpackage.model.core to javafx.fxml;
	// exports testpackage.model.enumeration to javafx.fxml;
	// exports testpackage.model.errors to javafx.fxml;
	// exports testpackage.model.generator to javafx.fxml;


	opens testpackage.gestiondinventaireyrm to javafx.fxml;

	opens db.configuration to javafx.fxml;
	opens db.errors to javafx.fxml;
	opens db.test to javafx.fxml;
	opens db.java to javafx.fxml;
	opens stateMachin to javafx.fxml;

	exports testpackage.gestiondinventaireyrm;
	//exports testpackage.model;
	// exports testpackage.model.core;
	// exports testpackage.model.enumeration;
	// exports testpackage.model.errors;
	// exports testpackage.model.generator;

	exports db.configuration;
	exports db.errors;
	exports db.test;
	exports db.java;

	exports stateMachin;

}
