/*
 * testpackage.gestiondinventaireyrm module that is visible to mvn package manager and build system
 * this file provide all requirements that depends on this project (UI , model , database)
 * generated by frontend developers 
 * @author aimeur abdelrahim , beliose ayoub
 * */
module testpackage.gestiondinventaireyrm {
	// external and internal librarys 
	requires javafx.controls;
	requires javafx.fxml;
	requires java.sql;
	requires javafx.base;

	requires org.controlsfx.controls;
	requires com.dlsc.formsfx;
	requires net.synedra.validatorfx;
	requires org.kordamp.ikonli.javafx;
	requires org.kordamp.bootstrapfx.core;
	opens testpackage.gestiondinventaireyrm to javafx.fxml;

	opens db.configuration to javafx.fxml;
	opens db.errors to javafx.fxml;
	opens db.test to javafx.fxml;
	opens db.java to javafx.fxml;
	opens stateMachin to javafx.fxml;

	exports testpackage.gestiondinventaireyrm;

	exports db.configuration;
	exports db.errors;
	exports db.test;
	exports db.java;
	exports stateMachin;
	exports temp;
	opens temp to javafx.fxml;
	opens testpackage.model.core to javafx.base;
    exports stateMachin.FourC;
    opens stateMachin.FourC to javafx.fxml;
    exports stateMachin.EmpC;
    opens stateMachin.EmpC to javafx.fxml;

}
